# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: README.md, .gitignore

# Site settings
title: My blog. My code. My Life
email: paul.negrutiu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://floridemai.github.io" # the base hostname & protocol for your site
twitter_username: flordemai
github_username:  floridemai

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'http://floridemai.github.io'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
